package com.example.reggelirutin

import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember

@Composable
fun rememberStrings(language: String): Map<String, String> {
    return remember(language) {
        when (language) {
            "English" -> mapOf(
                "title" to "Morning Routine",
                "total_time" to "Total Workout Time",
                "exercise_time" to "Exercise Time",
                "rest" to "Rest",
                "exercises" to "Exercises",
                "finish" to "Finish Workout",
                "start" to "Start",
                "pause" to "Pause",
                "reset" to "Reset",
                "set" to "Set",
                "history" to "History",
                "workouts_count" to "Workouts",
                "total_minutes" to "Total Min",
                "workout_tab" to "Workout",
                "history_tab" to "History",
                "about_title" to "About",
                "recent_workouts" to "Recent Workouts",
                "menu_languages" to "Languages",
                "menu_exercises" to "Exercises",
                "add_exercise" to "Add Exercise",
                "edit_exercise" to "Edit Exercise",
                "save" to "Save",
                "delete" to "Delete",
                "name" to "Name",
                "description" to "Description",
                "reps" to "Reps/Details",
                "sets_count" to "Total Sets",
                "update_available" to "Update Available",
                "new_version" to "New version",
                "current_version" to "Current version",
                "download_now" to "Download Now",
                "later" to "Later",
                "check_updates" to "Check for Updates",
                "no_update" to "Already on latest version",
                "update_error" to "Error checking for updates",
                "update_title" to "Application Updated",
                "migration_message" to "Would you like to clear your old workout history for a fresh start in this version?",
                "clear_history" to "Clear History",
                "keep_history" to "Keep History"
            )
            "Deutsch" -> mapOf(
                "title" to "Morgenroutine",
                "total_time" to "Gesamtzeit",
                "exercise_time" to "Übungszeit",
                "rest" to "Pause",
                "exercises" to "Übungen",
                "finish" to "Training beenden",
                "start" to "Start",
                "pause" to "Pause",
                "reset" to "Reset",
                "set" to "Satz",
                "history" to "Verlauf",
                "workouts_count" to "Trainings",
                "total_minutes" to "Gesamt Min",
                "workout_tab" to "Training",
                "history_tab" to "Verlauf",
                "about_title" to "Über",
                "recent_workouts" to "Letzte Trainingseinheiten",
                "menu_languages" to "Sprachen",
                "menu_exercises" to "Übungen",
                "add_exercise" to "Übung hinzufügen",
                "edit_exercise" to "Übung bearbeiten",
                "save" to "Speichern",
                "delete" to "Löschen",
                "name" to "Name",
                "description" to "Beschreibung",
                "reps" to "Wdh./Details",
                "sets_count" to "Sätze gesamt",
                "update_available" to "Update Verfügbar",
                "new_version" to "Neue Version",
                "current_version" to "Aktuelle Version",
                "download_now" to "Jetzt herunterladen",
                "later" to "Später",
                "check_updates" to "Nach Updates suchen",
                "no_update" to "Bereits auf der neuesten Version",
                "update_error" to "Fehler bei der Suche nach Updates",
                "update_title" to "Anwendung aktualisiert",
                "migration_message" to "Möchten Sie Ihren alten Trainingsverlauf löschen, um in dieser Version neu zu starten?",
                "clear_history" to "Verlauf löschen",
                "keep_history" to "Verlauf behalten"
            )
            else -> mapOf(
                "title" to "Reggeli Rutin",
                "total_time" to "Teljes edzés idő",
                "exercise_time" to "Gyakorlat idő",
                "rest" to "Pihenő",
                "exercises" to "Gyakorlatok",
                "finish" to "Edzés Befejezése",
                "start" to "Indítás",
                "pause" to "Szünet",
                "reset" to "Reset",
                "set" to "Sorozat",
                "history" to "Történet",
                "workouts_count" to "Edzések",
                "total_minutes" to "Összes perc",
                "workout_tab" to "Edzés",
                "history_tab" to "Történet",
                "about_title" to "Névjegy",
                "recent_workouts" to "Legutóbbi edzések",
                "menu_languages" to "Nyelvek",
                "menu_exercises" to "Gyakorlatok",
                "add_exercise" to "Gyakorlat hozzáadása",
                "edit_exercise" to "Gyakorlat szerkesztése",
                "save" to "Mentés",
                "delete" to "Törlés",
                "name" to "Név",
                "description" to "Leírás",
                "reps" to "Ismétlés/Részletek",
                "sets_count" to "Összes sorozat",
                "update_available" to "Frissítés elérhető",
                "new_version" to "Új verzió",
                "current_version" to "Jelenlegi verzió",
                "download_now" to "Letöltés most",
                "later" to "Később",
                "check_updates" to "Frissítés keresése",
                "no_update" to "A legfrissebb verziót használod",
                "update_error" to "Hiba a frissítés ellenőrzésekor",
                "update_title" to "Alkalmazás frissítve",
                "migration_message" to "Szeretné törölni a korábbi edzés előzményeket a tiszta kezdéshez ebben a verzióban?",
                "clear_history" to "Előzmények törlése",
                "keep_history" to "Megtartás"
            )
        }
    }
}
