package com.example.reggelirutin

import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember

@Composable
fun rememberStrings(language: String): Map<String, String> {
    return remember(language) {
        when (language) {
            "English" -> mapOf(
                "title" to "Morning Routine",
                "total_time" to "Total Workout Time",
                "exercise_time" to "Exercise Time",
                "rest" to "Rest",
                "exercises" to "Exercises",
                "finish" to "Finish Workout",
                "start" to "Start",
                "pause" to "Pause",
                "reset" to "Reset",
                "set" to "Set",
                "history" to "History",
                "workouts_count" to "Workouts",
                "total_minutes" to "Total Min",
                "workout_tab" to "Workout",
                "history_tab" to "History",
                "about_title" to "About",
                "recent_workouts" to "Recent Workouts",
                "menu_languages" to "Languages",
                "menu_exercises" to "Exercises",
                "add_exercise" to "Add Exercise",
                "edit_exercise" to "Edit Exercise",
                "save" to "Save",
                "delete" to "Delete",
                "name" to "Name",
                "description" to "Description",
                "reps" to "Reps/Details",
                "sets_count" to "Total Sets",
                "update_available" to "Update Available",
                "new_version" to "New version",
                "current_version" to "Current version",
                "download_now" to "Download Now",
                "later" to "Later",
                "check_updates" to "Check for Updates",
                "no_update" to "Already on latest version",
                "update_error" to "Error checking for updates",
                "update_title" to "Application Updated",
                "migration_message" to "Would you like to clear your old workout history for a fresh start in this version?",
                "clear_history" to "Clear History",
                "keep_history" to "Keep History",
                "select_day" to "Active on:",
                "day_1" to "Mon", "day_2" to "Tue", "day_3" to "Wed", "day_4" to "Thu", "day_5" to "Fri", "day_6" to "Sat", "day_7" to "Sun",
                "mode_normal" to "Normal",
                "mode_extra" to "Extra",
                "select_mode" to "Choose Mode",
                "groups" to "Exercise Groups",
                "add_group" to "Add Group",
                "edit_group" to "Edit Group",
                "group_name" to "Group Name",
                "all_groups" to "All Groups",
                "showcase_welcome" to "Welcome to the new version!",
                "showcase_modes" to "Choose Normal for your daily routine or Extra to focus on a specific group.",
                "showcase_days" to "You can switch between days here. Every day can have different exercises.",
                "showcase_timers" to "Track your total workout time and individual exercise/rest times here.",
                "showcase_exercises" to "Click on a set to mark it as done. The app will automatically guide you to the next set.",
                "showcase_finish" to "When you're done with everything, click here to save your workout.",
                "showcase_menu" to "Use the menu to manage your exercises, groups, or change the language.",
                "next" to "Next",
                "demo" to "Demo",
                "got_it" to "Got it"
            )
            "Deutsch" -> mapOf(
                "title" to "Morgenroutine",
                "total_time" to "Gesamtzeit",
                "exercise_time" to "Übungszeit",
                "rest" to "Pause",
                "exercises" to "Übungen",
                "finish" to "Training beenden",
                "start" to "Start",
                "pause" to "Pause",
                "reset" to "Reset",
                "set" to "Satz",
                "history" to "Verlauf",
                "workouts_count" to "Trainings",
                "total_minutes" to "Gesamt Min",
                "workout_tab" to "Training",
                "history_tab" to "Verlauf",
                "about_title" to "Über",
                "recent_workouts" to "Letzte Trainingseinheiten",
                "menu_languages" to "Sprachen",
                "menu_exercises" to "Übungen",
                "add_exercise" to "Übung hinzufügen",
                "edit_exercise" to "Übung bearbeiten",
                "save" to "Speichern",
                "delete" to "Löschen",
                "name" to "Name",
                "description" to "Beschreibung",
                "reps" to "Wdh./Details",
                "sets_count" to "Sätze gesamt",
                "update_available" to "Update Verfügbar",
                "new_version" to "Neue Version",
                "current_version" to "Aktuelle Version",
                "download_now" to "Jetzt herunterladen",
                "later" to "Später",
                "check_updates" to "Nach Updates suchen",
                "no_update" to "Bereits auf der neuesten Version",
                "update_error" to "Fehler bei der Suche nach Updates",
                "update_title" to "Anwendung aktualisiert",
                "migration_message" to "Möchten Sie Ihren alten Trainingsverlauf löschen, um in dieser Version neu zu starten?",
                "clear_history" to "Verlauf löschen",
                "keep_history" to "Verlauf behalten",
                "select_day" to "Aktiv am:",
                "day_1" to "Mo", "day_2" to "Di", "day_3" to "Mi", "day_4" to "Do", "day_5" to "Fr", "day_6" to "Sa", "day_7" to "So",
                "mode_normal" to "Normal",
                "mode_extra" to "Extra",
                "select_mode" to "Modus wählen",
                "groups" to "Gyakorlat csoportok",
                "add_group" to "Csoport hozzáadása",
                "edit_group" to "Csoport szerkesztése",
                "group_name" to "Csoport neve",
                "all_groups" to "Összes csoport",
                "showcase_welcome" to "Willkommen in der neuen Version!",
                "showcase_modes" to "Wählen Sie 'Normal' für Ihre Routine oder 'Extra' für eine bestimmte Gruppe.",
                "showcase_days" to "Hier können Sie zwischen den Tagen wechseln. Jeder Tag hat eigene Übungen.",
                "showcase_timers" to "Hier sehen Sie die Gesamtzeit und die Zeit für Übungen/Pausen.",
                "showcase_exercises" to "Klicken Sie auf einen Satz, um ihn abzuschließen. Die App führt Sie automatisch weiter.",
                "showcase_finish" to "Wenn Sie fertig sind, klicken Sie hier, um das Training zu speichern.",
                "showcase_menu" to "Nutzen Sie das Menü, um Übungen und Gruppen zu verwalten.",
                "next" to "Weiter",
                "demo" to "Demo",
                "got_it" to "Verstanden"
            )
            else -> mapOf(
                "title" to "Reggeli Rutin",
                "total_time" to "Teljes edzés idő",
                "exercise_time" to "Gyakorlat idő",
                "rest" to "Pihenő",
                "exercises" to "Gyakorlatok",
                "finish" to "Edzés Befejezése",
                "start" to "Indítás",
                "pause" to "Szünet",
                "reset" to "Reset",
                "set" to "Sorozat",
                "history" to "Történet",
                "workouts_count" to "Edzések",
                "total_minutes" to "Összes perc",
                "workout_tab" to "Edzés",
                "history_tab" to "Történet",
                "about_title" to "Névjegy",
                "recent_workouts" to "Legutóbbi edzések",
                "menu_languages" to "Nyelvek",
                "menu_exercises" to "Gyakorlatok",
                "add_exercise" to "Gyakorlat hozzáadása",
                "edit_exercise" to "Gyakorlat szerkesztése",
                "save" to "Mentés",
                "delete" to "Törlés",
                "name" to "Név",
                "description" to "Leírás",
                "reps" to "Ismétlés/Részletek",
                "sets_count" to "Összes sorozat",
                "update_available" to "Frissítés elérhető",
                "new_version" to "Új verzió",
                "current_version" to "Jelenlegi verzió",
                "download_now" to "Letöltés most",
                "later" to "Később",
                "check_updates" to "Frissítés keresése",
                "no_update" to "A legfrissebb verziót használod",
                "update_error" to "Hiba a frissítés ellenőrzésekor",
                "update_title" to "Alkalmazás frissítve",
                "migration_message" to "Szeretné törölni a korábbi edzés előzményeket a tiszta kezdéshez ebben a verzióban?",
                "clear_history" to "Előzmények törlése",
                "keep_history" to "Megtartás",
                "select_day" to "Aktív nap:",
                "day_1" to "H", "day_2" to "K", "day_3" to "Sze", "day_4" to "Cs", "day_5" to "P", "day_6" to "Szo", "day_7" to "V",
                "mode_normal" to "Normál",
                "mode_extra" to "Extra",
                "select_mode" to "Válassz módot",
                "groups" to "Gyakorlat csoportok",
                "add_group" to "Csoport hozzáadása",
                "edit_group" to "Csoport szerkesztése",
                "group_name" to "Csoport neve",
                "all_groups" to "Összes csoport",
                "showcase_welcome" to "Üdvözlünk az új verzióban!",
                "showcase_modes" to "Válaszd a Normált a napi rutinhoz, vagy az Extrát egy konkrét csoporthoz.",
                "showcase_days" to "Itt válthatsz a napok között. Minden naphoz más gyakorlatok tartozhatnak.",
                "showcase_timers" to "Itt követheted a teljes időt és az aktuális gyakorlat/pihenő idejét.",
                "showcase_exercises" to "Kattints egy sorozatra, ha kész vagy. Az app automatikusan léptet a következőhöz.",
                "showcase_finish" to "Ha minden kész, itt tudod elmenteni az edzést.",
                "showcase_menu" to "A menüben kezelheted a gyakorlatokat, csoportokat vagy válthatsz nyelvet.",
                "next" to "Következő",
                "demo" to "Demo",
                "got_it" to "Értem"
            )
        }
    }
}
